#:include screens/start_screen.kv
#:include screens/source_screen.kv
#:include screens/local_files_screen.kv
#:include screens/login_screen.kv
#:include screens/loading_screen.kv
#:include screens/browse_files_screen.kv
#:include screens/session_screen.kv
#:include screens/tester_screen.kv
#:include screens/session_over_screen.kv
#:include screens/spotify_playlists_screen.kv
#: include screens/spotify_search_screen.kv